version: "3.7"

# Dockerfileで定義したアプリケーションコンテナの構築で必要な情報を提供する
x-app: &app
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    args:
      RUBY_VERSION: '2.6.6'
      PG_MAJOR: '11'
      NODE_MAJOR: '14'
      YARN_VERSION: '1.21.1'
      BUNDLER_VERSION: '2.1.4'
  environment: &env
    RAILS_ENV: ${RAILS_ENV:-development}
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp

# Rubyのサービスで共有するボリュームを提供する
x-backend-volumes: &backend-volumes
  volumes:
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
    - .dockerdev/.bashrc:/root/.bashrc:ro
    - .:/app:cached
    - bundle:/bundle

# Rubyのサービスで共有する振る舞いを提供する
x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true 
  environment:
    <<: *env
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
  depends_on:
    - postgres

services:
  runner:
    <<: *backend
    <<: *backend-volumes
    command: >
      bash -c "bundle install &&
      bin/rake db:create &&
      bin/rake db:migrate &&
      bash"
    ports:
      - '3002:3002'

  postgres:
    image: postgres:11.5
    volumes:
      - .dockerdev/init_postgres/:/docker-entrypoint-initdb.d/
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - '5432:5432'

volumes:
  postgres:
  bundle:
