default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  database: test_sample_db
  password:
  host: 127.0.0.1
  port: 5432

development:
  <<: *default

test:
  <<: *default
